### ISSUE TITLE
The API hear-beat never reaches a time-out when the node closes the connection:

### ISSUE THREAD

**Issue by centrys-otniel** [aionnetwork/aion_api#27]
Steps to reproduce:

1. Connect API to a working Node
2. Shutdown Node

Expected: 
* API heatbeat time-out and disconnect

Actual:
* API hangs

**Comment by AionJayT** [comment]
@centrys-otniel, https://github.com/aionnetwork/aion/pull/505 will solve some of the API shutdown issues. this week we will fix the client API shutdown process.

**Comment by AionJayT** [comment]
fixed in api v0.1.8
