### ISSUE TITLE
getSyncInfo returns suspicios numbers for chainBestBlock - API v0.1.18

### ISSUE THREAD

**Issue by centrys-otniel** [aionnetwork/aion_api#28]
`API.getNet().syncInfo()` returns unexpected values - i.e. the reported chainBestBlock is too low. 

These are the numbers reported by the Java API:
`Syncing: true, chainBest: 405384, netBest: 405785`

These are the numbers reported by the web3 API:
`aion-127.0.0.1:8545> eth.syncing`
`{ currentBlock: 405785,`
`  highestBlock: 405384,`
`  startingBlock: 400437 }`

These are the last lines in the kernel's logs reffering to these node numbers:
`18-06-12 09:46:49.482 INFO  SYNC [p2p-worker-9]: <import-status: node = c33d5a, hash = be4867, number = 405384, txs = 0, result = IMPORTED_BEST, time elapsed = 1 ms>`
`18-06-12 10:58:36.047 INFO  SYNC [p2p-worker-6]: <import-status: node = c33d22, hash = 4c3620, number = 405785, txs = 0, result = IMPORTED_BEST, time elapsed = 0 ms>`

One thing that stood out is that the block reported as the chainBest was the first block processed by a `p2p-worker-*` thread after a batch of blocks processed by `sync-ib` nodes:
![screenshot from 2018-06-12 11-37-19](https://user-images.githubusercontent.com/37304045/41279549-7748b502-6e35-11e8-8dd6-9de970668349.png)

From these numbers I understand that I should not be able to access blocks that have higher numbers than **405384**, but fom the Java API I can do that. This suggests that the number reported as `chainBestBlock` is not acurate.

You can see below that I can get TransactionDetails from a Block that is higher than the current chainBestBlock:
**405384 < 405583**
![screenshot from 2018-06-12 10-58-59](https://user-images.githubusercontent.com/37304045/41279797-16fab6fe-6e36-11e8-872e-e89a9bb55c1a.png)

![screenshot from 2018-06-12 10-59-01](https://user-images.githubusercontent.com/37304045/41279978-84011194-6e36-11e8-83a3-b7b12712dd82.png)

L.E: Kernel version is: v0.2.7.1bbeec1

**Comment by AionJayT** [comment]
fixed in https://github.com/aionnetwork/aion_api/commit/9551b207933ddecf24e0cc664a71a4a0459d5590

**Comment by centrys-otniel** [comment]
@AionJayT We integrated the new API jar and used it with the 0.2.8 kernel. While the node was syncing we were receiving correct numbers for chain-best and network best.
However, when the node was effectively synced, we were getting rather weirn numbers:
1. If the node had been running for a while, the chain best is a significantly larger number than the network best:
![screenshot from 2018-06-18 11-09-14](https://user-images.githubusercontent.com/37304045/41525208-ddd75f78-72e8-11e8-9825-988779552ac3.png)

2. If the node was just started, the numbers stay in a range 1-2 from each other but they drift apart after a while, with the chain best becoming larger than the network best:
![screenshot from 2018-06-18 11-10-30](https://user-images.githubusercontent.com/37304045/41525225-eac884fa-72e8-11e8-897c-69d547558b19.png)


Also, as you can see, the SyncInfo.syncing boolean is always true. Maybe I'm misunderstanding the meaning it has, but I was expecting this to be false when the node is in a synced state (though this is not really critical for us since we don't rely on it's meaning for now)

**Comment by AionJayT** [comment]
@centrys-otniel this should be the kernel issues. The syncMgr maybe doesn't update the status on-time
 I will take a look.

**Comment by AionJayT** [comment]
fix the issue in the kernel PR.
the kernel binary will publish in the mid of July
https://github.com/aionnetwork/aion/pull/544
