### ISSUE TITLE
implements encrypted zmq connection (client and server-side)

### ISSUE THREAD

**Issue by ali-sharif** [aionnetwork/aion_api#5]

**Comment by AionJayT** [comment]
for the current zmq implementation, need to exchange the key before setup the socket connection. It needs to open another port to achieve this feature. can discuss together.

**Comment by AionJayT** [comment]
@ali-sharif implemented in https://github.com/aionnetwork/aion_api/commit/c03b1688edeebb4076dbc4f6619a2ce898fa573b
and
https://github.com/aionnetwork/aion/commit/49c46a7e66d962521f34288886ea3179e99162d5
