### ISSUE TITLE
accounts/search/findByAddr not working

### ISSUE THREAD

**Issue by pfuhrmann** [aionnetwork/aion_api#8]
When I check in the web3 I can see my accounts:
```
aion-127.0.0.1:8545> eth.accounts
[ '0xd7803ef36bb407c73836498d14b2bc919e3dc109189cc18c2298752be9c60541',
  '0x65607418bdb5c5e02b88b91eb27b2a06bbcca0d7a6ed9f17f044deed94a20a31',
  '0xd23d6dd3aef5f4550d5c2ea76868a3ad2262f13d2733f9a92eb93b24f7b6415f',
  '0x65742fab87870d2f4593278f17ce4edaae8f42efe30bffc515c28575e65ce2ab',
  '0x68a8635329677e2c2bbd952c2ebbf12ae47e4d1191b29c207084acfaa4dd43be',
  '0x1247934d3551a2644115c665d4e03489eb0b5814ef94993c39f023dd4cf18d04' ]
```

However  when I try to query them through the API it is not finding any of them
https://api.aion.network/aion/accounts/search/findByAddr?addr=0xd7803ef36bb407c73836498d14b2bc919e3dc109189cc18c2298752be9c60541

https://api.aion.network/aion/accounts/search/findByAddr?addr=0x65742fab87870d2f4593278f17ce4edaae8f42efe30bffc515c28575e65ce2ab

https://api.aion.network/aion/accounts/search/findByAddr?addr=0x1247934d3551a2644115c665d4e03489eb0b5814ef94993c39f023dd4cf18d04

**Comment by AionJayT** [comment]
@pfuhrmann sorry for late reply, if this issue still happens in the kernel build (v0.2.5 or above). Please submit the issue to the [aion web3](https://github.com/aionnetwork/aion_web3) repo. Thanks
